server:
  port: 8080

spring:

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  thymeleaf:
    cache: false
    check-template: true
    prefix: classpath:templates/
    suffix: .html

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/project?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
      username: ${db_userName}
      password: ${db_userPwd}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google_id}
            client-secret: ${google_pwd}
            scope:
              - email
              - profile
          naver:
            client-id: ${naver_id}
            client-secret: ${naver_pwd}
            scope:
              - name
              - email
              - nickname
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  # mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail_id}
    password: ${gmail_pwd}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          timeout: 50000
          starttls:
            enable: true
  data:
    redis:
      mail:
        host: localhost
        port: 6379

kakao:
  maps:
    api:
      key: b0724bf330998cfd60824078a8ffae4e